' статусы описывают жизненный цикл пользовательской сессии в тг-боте
' статусы используются как значение ключа session:{telegram_id}:state в db0 Redis
@@startuml
start
-> Пользователь\nоткрыл тг-бот;
:IDLE;

fork
-> Пользователь выбрал\nзагрузку файла;
:AWAITING_FILE;
-> Пользователь\nзагрузил файл;
:FILE_UPLOADED;
fork again;
-> Пользователь выбрал\nввод текста;
:AWAITING_TEXT;
-> Пользователь вставил\nтекст договора;
:TEXT_ENTERED;
fork again;
-> Пользователь выбрал\nприкрепление ссылки;
:AWAITING_LINK;
-> Пользователь указал\nссылку на GoogleDocs;
:LINK_ENTERED;
fork again;
-> Пользователь выбрал\nзагрузку изображения;
:AWAITING_IMAGE;
-> Пользователь\nзагрузил изображение;
:IMAGE_UPLOADED;
end fork

-> Выполняется\nАнализ договора;
:ANALYZING;

if (Анализ выполнен\nуспешно?)
    -> Да;
    :COMPLETED;
    note left
    Результат выполнения 
    Анализа готов и
    представлен пользователю
    end note
    -> Ожидание обратной\nсвязи от пользователя;
    :AWAITING_FEEDBACK;
else (нет)
    -> Нет;
    :ERROR;
    note right
    Ошибка в ходе
    выполнения Анализа
    end note
endif

end
@@enduml